version: 0.0
files:
  - source: /
    destination: /ecs_cicd_demo
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "ecs-cicd-demo"
          ContainerPort: 80
