version: "3.7"
services:
  web:
    container_name: web-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - .:/ecs_cicd_demo
    entrypoint:
      - ./docker_script.sh
